alias: BYD Akkusteuerung
description: ""
trigger:
  - platform: state
    entity_id:
      - input_select.byd_akkusteuerung
      - input_number.byd_akkusteuerung_ladestaerke_soll
      - input_number.byd_akkusteuerung_entladestaerke_soll
      - input_number.byd_akkusteuerung_02c_ladestaerke
    from: null
    to: null
    for:
      hours: 0
      minutes: 0
      seconds: 1
  - platform: time_pattern
    minutes: /30
    enabled: true
  - platform: homeassistant
    event: start
condition: []
action:
  - alias: Wenn BYD Akku schnell Laden ...
    if:
      - condition: state
        entity_id: input_select.byd_akkusteuerung
        state: BYD Akku schnell Laden
    then:
      - service: modbus.write_register
        data:
          hub: sma-hm
          address: 40151
          slave: 2
          value:
            - 0
            - 802
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: modbus.write_register
        data:
          hub: sma-hm
          address: 40149
          slave: 2
          value:
            - 65535
            - >-
              {{ 65535 -
              states('input_number.byd_akkusteuerung_ladestaerke_soll') | int }}
  - alias: Wenn BYD Akku schnell Entaden ...
    if:
      - condition: state
        entity_id: input_select.byd_akkusteuerung
        state: BYD Akku schnell Entladen
    then:
      - service: modbus.write_register
        data:
          hub: sma-hm
          address: 40151
          slave: 2
          value:
            - 0
            - 802
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: modbus.write_register
        data:
          hub: sma-hm
          address: 40149
          slave: 2
          value:
            - 0
            - >-
              {{ states('input_number.byd_akkusteuerung_entladestaerke_soll') |
              int }}
  - alias: Wenn BYD Akku Pause ...
    if:
      - condition: state
        entity_id: input_select.byd_akkusteuerung
        state: BYD Akku Pause
    then:
      - service: modbus.write_register
        data:
          hub: sma-hm
          address: 40151
          slave: 2
          value:
            - 0
            - 802
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: modbus.write_register
        data:
          hub: sma-hm
          address: 40149
          slave: 2
          value:
            - 65535
            - 65534
  - alias: Wenn BYD Automatik  ...
    if:
      - condition: state
        entity_id: input_select.byd_akkusteuerung
        state: BYD Akku Automatisch
    then:
      - service: modbus.write_register
        data:
          hub: sma-hm
          address: 40151
          slave: 2
          value:
            - 0
            - 803
  - alias: Wenn BYD Akku 0.2C Laden
    if:
      - condition: state
        entity_id: input_select.byd_akkusteuerung
        state: BYD Akku 0.2C Laden
    then:
      - service: modbus.write_register
        data:
          hub: sma-hm
          address: 40151
          slave: 2
          value:
            - 0
            - 802
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: modbus.write_register
        data:
          hub: sma-hm
          address: 40149
          slave: 2
          value:
            - 65535
            - >-
              {{ 65535 -
              states('input_number.byd_akkusteuerung_02c_ladestaerke') | int }}
mode: single
