alias: Akku Lade- Entladesteuerung (inkl. AC-Überschuss)
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.tibber_price_level
    id: Tibber Preislevel Änderung
    enabled: false
    from: null
    to: null
  - platform: state
    entity_id:
      - input_boolean.akku_opti_automatik
    id: Akku Opti-Automatik AN/AUS
  - platform: state
    entity_id:
      - sensor.sn_3017XXXXXX_battery_soc_total
    id: BYD Änderung
  - platform: numeric_state
    entity_id:
      - sensor.sn_3017XXXXXX_battery_soc_total
    above: 99
    id: Speicher ist voll
  - platform: numeric_state
    entity_id:
      - sensor.sn_3017XXXXXX_battery_soc_total
    above: 49
    id: Speicher ist über 50%
  - platform: numeric_state
    entity_id:
      - sensor.mindestentladepreis
    below: sensor.electricity_price_meinestrasse_123
    id: Entladeschwelle
    enabled: true
  - platform: numeric_state
    entity_id:
      - sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
    below: input_number.akkusteuerung_ab_welchem_restertrag_vollladen
    id: restliche Verbleibende PV unter Schwelle heute
  - platform: numeric_state
    entity_id:
      - sensor.sn_3017XXXXXX_pv_power
    above: input_number.sma_hybrid_wr_ac_ueberschuss_grenze
    id: AC-Überschuss
    for:
      hours: 0
      minutes: 0
      seconds: 30
  - platform: numeric_state
    entity_id:
      - sensor.maximaler_ueberschuss_fuer_akkuladung_watt
    for:
      hours: 0
      minutes: 1
      seconds: 0
    above: input_number.byd_akkusteuerung_02c_ladestaerke
    id: Akku Überschuss über 0.2C
  - platform: numeric_state
    entity_id:
      - sensor.maximaler_ueberschuss_fuer_akkuladung_watt
    for:
      hours: 0
      minutes: 0
      seconds: 15
    below: 2560
    id: Akku Überschuss unter 0.2C
  - platform: numeric_state
    entity_id:
      - sensor.sn_3017XXXXXX_metering_power_absorbed
    for:
      hours: 0
      minutes: 0
      seconds: 15
    below: 2560
    id: Netzbezug
    above: 10
  - platform: numeric_state
    entity_id:
      - sensor.sn_3017XXXXXX_battery_power_charge_total
    above: 3000
    id: Akku Charge-Power über 3000
    for:
      hours: 0
      minutes: 0
      seconds: 15
  - platform: numeric_state
    entity_id:
      - sensor.sn_3017XXXXXX_pv_power
    for:
      hours: 0
      minutes: 0
      seconds: 30
    id: AC-Überschuss
    above: input_number.sma_hybrid_wr_ac_ueberschuss_grenze
  - platform: numeric_state
    entity_id:
      - sensor.sn_3017XXXXXX_pv_power
    for:
      hours: 0
      minutes: 0
      seconds: 30
    id: AC-Überschuss-Aus
    below: input_number.sma_hybrid_wr_ac_ueberschuss_grenze
condition: []
action:
  - alias: Zwischen Speicherszenarien wählen
    choose:
      - conditions:
          - condition: trigger
            id:
              - Akku Überschuss über 0.2C
              - Speicher ist über 50%
              - Akku Überschuss unter 0.2C
              - Akku Charge-Power über 3000
              - AC-Überschuss-Aus
              - AC-Überschuss
              - restliche Verbleibende PV unter Schwelle heute
              - Akku Opti-Automatik AN/AUS
          - condition: state
            entity_id: input_boolean.akku_opti_automatik
            state: "on"
          - condition: state
            entity_id: input_boolean.hausakku_aus_netz_laden
            state: "off"
          - condition: sun
            before: sunset
            after: sunrise
        sequence:
          - if:
              - condition: numeric_state
                entity_id: sensor.sn_3017XXXXXX_pv_power
                above: input_number.sma_hybrid_wr_ac_ueberschuss_grenze
              - condition: numeric_state
                entity_id: sensor.sn_3017XXXXXX_battery_soc_total
                below: "100"
            then:
              - service: input_number.set_value
                target:
                  entity_id: input_number.byd_akkusteuerung_ladestaerke_soll
                data:
                  value: 100
              - service: input_select.select_option
                metadata: {}
                data:
                  option: BYD Akku schnell Laden
                target:
                  entity_id: input_select.byd_akkusteuerung
              - stop: fertig
            alias: Bei AC Überschuss diesen in den Akku Laden
          - if:
              - condition: numeric_state
                entity_id: sensor.sn_3017XXXXXX_battery_soc_total
                above: 99
            then:
              - service: input_number.set_value
                target:
                  entity_id: input_number.byd_akkusteuerung_ladestaerke_soll
                data:
                  value: 100
              - service: input_select.select_option
                metadata: {}
                data:
                  option: BYD Akku Automatisch
                target:
                  entity_id: input_select.byd_akkusteuerung
              - stop: fertig
            alias: Bei vollem Akku im Zweifel auf Automatisch schalten
          - alias: >-
              Ab über Restladeschwelle den Akku voll machen mit 0.2C bei SoC
              unter 50%
            if:
              - condition: numeric_state
                entity_id: >-
                  sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
                enabled: true
                above: input_number.akkusteuerung_ab_welchem_restertrag_vollladen
              - condition: numeric_state
                entity_id: sensor.sn_3017XXXXXX_battery_soc_total
                above: 0
                below: 50
              - condition: sun
                before: sunset
                after: sunrise
              - condition: numeric_state
                entity_id: sensor.maximaler_ueberschuss_fuer_akkuladung_watt
                above: 2500
            then:
              - service: input_select.select_option
                metadata: {}
                data:
                  option: BYD Akku 0.2C Laden
                target:
                  entity_id: input_select.byd_akkusteuerung
              - stop: fertig
          - alias: >-
              Ab unter Restladeschwelle den Akku voll machen mit 0.2C bei SoC
              unter 90%
            if:
              - condition: numeric_state
                entity_id: >-
                  sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
                below: input_number.akkusteuerung_ab_welchem_restertrag_vollladen
                enabled: true
              - condition: numeric_state
                entity_id: sensor.sn_3017XXXXXX_battery_soc_total
                above: 0
                below: 90
              - condition: numeric_state
                entity_id: sensor.maximaler_ueberschuss_fuer_akkuladung_watt
                above: 2600
            then:
              - service: input_select.select_option
                metadata: {}
                data:
                  option: BYD Akku 0.2C Laden
                target:
                  entity_id: input_select.byd_akkusteuerung
              - stop: fertig
          - alias: >-
              Ab unter Restladeschwelle den Akku voll machen mit 1kW bei SoC
              über 90%
            if:
              - condition: numeric_state
                entity_id: >-
                  sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
                below: input_number.akkusteuerung_ab_welchem_restertrag_vollladen
                enabled: true
              - condition: numeric_state
                entity_id: sensor.sn_3017XXXXXX_battery_soc_total
                above: 89
                below: 100
              - condition: numeric_state
                entity_id: sensor.maximaler_ueberschuss_fuer_akkuladung_watt
                above: 1100
            then:
              - service: input_number.set_value
                target:
                  entity_id: input_number.byd_akkusteuerung_ladestaerke_soll
                data:
                  value: 1000
              - service: input_select.select_option
                metadata: {}
                data:
                  option: BYD Akku schnell Laden
                target:
                  entity_id: input_select.byd_akkusteuerung
              - stop: fertig
          - alias: >-
              Ab unter 35kWh Automatisch bei weniger als 1100W und unter 100%
              SoC
            if:
              - condition: numeric_state
                entity_id: >-
                  sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
                below: input_number.akkusteuerung_ab_welchem_restertrag_vollladen
                enabled: true
              - condition: numeric_state
                entity_id: sensor.maximaler_ueberschuss_fuer_akkuladung_watt
                below: 1100
            then:
              - service: input_select.select_option
                metadata: {}
                data:
                  option: BYD Akku Automatisch
                target:
                  entity_id: input_select.byd_akkusteuerung
              - stop: fertig
          - alias: >-
              Bei über 35kWh Rest und Akku 50% ODER Akku auf 100% den Akku
              Pausieren
            if:
              - condition: or
                conditions:
                  - condition: and
                    conditions:
                      - condition: numeric_state
                        entity_id: >-
                          sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
                        enabled: true
                        above: >-
                          input_number.akkusteuerung_ab_welchem_restertrag_vollladen
                      - condition: numeric_state
                        entity_id: sensor.sn_3017XXXXXX_battery_soc_total
                        above: 47
                  - condition: and
                    conditions:
                      - condition: numeric_state
                        entity_id: >-
                          sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
                        enabled: true
                        above: >-
                          input_number.akkusteuerung_ab_welchem_restertrag_vollladen
                      - condition: numeric_state
                        entity_id: sensor.sn_3017XXXXXX_battery_soc_total
                        above: 99
            then:
              - service: input_number.set_value
                target:
                  entity_id: input_number.byd_akkusteuerung_ladestaerke_soll
                data:
                  value: 500
                enabled: false
              - service: input_select.select_option
                metadata: {}
                data:
                  option: BYD Akku Pause
                target:
                  entity_id: input_select.byd_akkusteuerung
      - conditions:
          - condition: trigger
            id:
              - Speicher ist voll
          - condition: state
            entity_id: input_boolean.hausakku_aus_netz_laden
            state: "on"
            enabled: true
        sequence:
          - service: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.hausakku_aus_netz_laden
          - service: input_number.set_value
            data:
              value: >-
                {{ states('sensor.electricity_price_meinestrasse_123')| float(0)
                }}
            target:
              entity_id: input_number.ladepreis
            alias: Ladepreis Helfer nach aktuellem Strompreis
          - service: input_select.select_option
            metadata: {}
            data:
              option: BYD Akku Pause
            target:
              entity_id: input_select.byd_akkusteuerung
      - conditions:
          - condition: trigger
            id:
              - Entladeschwelle
              - Netzbezug
        sequence:
          - service: input_select.select_option
            metadata: {}
            data:
              option: BYD Akku Automatisch
            target:
              entity_id: input_select.byd_akkusteuerung
            alias: BYD Akku Automatisch
      - conditions:
          - condition: trigger
            id:
              - sehr günstig
              - günstig
          - condition: numeric_state
            entity_id: sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
            below: 20
          - condition: numeric_state
            entity_id: sensor.sn_3017XXXXXX_battery_soc_total
            below: 60
          - condition: sun
            before: sunrise
            after: sunset
        sequence:
          - service: input_select.select_option
            metadata: {}
            data:
              option: BYD Akku Pause
            target:
              entity_id: input_select.byd_akkusteuerung
        alias: Akku Pause wenn Prognose schlecht und aufsparen
  - alias: Zwischen Tibber Aktionen wählen
    choose:
      - conditions:
          - condition: trigger
            id:
              - Tibber Preislevel Änderung
          - condition: trigger
            id:
              - sehr günstig
              - günstig
              - normal
          - condition: trigger
            id:
              - sehr günstig
              - günstig
          - condition: trigger
            id:
              - sehr günstig
              - günstig
          - condition: trigger
            id:
              - teuer
              - sehr teuer
              - normal
        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: sensor.sn_3017XXXXXX_battery_soc_total
                    below: 50
                  - condition: numeric_state
                    entity_id: >-
                      sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
                    below: 10
                  - condition: numeric_state
                    entity_id: sensor.tibber_preisspanne_heute
                    above: 8
                  - condition: numeric_state
                    entity_id: sensor.tibber_aktueller_preis_ist_tageshochstpreis
                    below: 20
                  - condition: state
                    entity_id: input_boolean.akku_nach_preis_laden
                    state: "on"
                sequence:
                  - service: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.speicher_eco_netzladen
                    data: {}
                  - service: input_boolean.turn_on
                    target:
                      entity_id:
                        - input_boolean.hausakku_aus_netz_laden
                    data: {}
                  - service: input_boolean.turn_on
                    target:
                      entity_id:
                        - input_boolean.hausakku_aus_netz_laden
                        - input_boolean.tibber_speicher_wurde_netzgeladen
                    data: {}
                  - service: input_select.select_option
                    metadata: {}
                    data:
                      option: BYD Akku schnell Laden
                    target:
                      entity_id: input_select.byd_akkusteuerung
                alias: Akku tatsächlich Laden wenn es sich lohnt und aktiviert
              - conditions:
                  - condition: numeric_state
                    entity_id: >-
                      sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
                    above: 25
                  - condition: numeric_state
                    entity_id: sensor.sn_3017XXXXXX_battery_soc_total
                    above: 60
                  - condition: sun
                    before: sunrise
                    after: sunset
                  - condition: numeric_state
                    entity_id: sensor.maximaler_ueberschuss_fuer_akkuladung_watt
                    below: 1
                sequence:
                  - service: input_select.select_option
                    metadata: {}
                    data:
                      option: BYD Akku Automatisch
                    target:
                      entity_id: input_select.byd_akkusteuerung
                  - service: input_boolean.turn_off
                    target:
                      entity_id:
                        - input_boolean.hausakku_aus_netz_laden
                        - input_boolean.tibber_speicher_wurde_netzgeladen
                    data: {}
                alias: >-
                  Wenn der PV-Ertrag gut wird Akku Automatisch und Ladung
                  freigeben (ohne PV)
              - conditions:
                  - condition: numeric_state
                    entity_id: >-
                      sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
                    above: 10
                  - condition: sun
                    before: sunset
                    after: sunrise
                sequence:
                  - service: input_select.select_option
                    metadata: {}
                    data:
                      option: BYD Akku Automatisch
                    target:
                      entity_id: input_select.byd_akkusteuerung
                    enabled: false
                  - service: input_boolean.turn_off
                    target:
                      entity_id:
                        - input_boolean.hausakku_aus_netz_laden
                        - input_boolean.tibber_speicher_wurde_netzgeladen
                    data: {}
                    enabled: false
              - conditions:
                  - condition: or
                    conditions:
                      - condition: numeric_state
                        entity_id: sensor.solcast_pv_forecast_prognose_morgen
                        above: 25
                      - condition: numeric_state
                        entity_id: >-
                          sensor.solcast_pv_forecast_prognose_verbleibende_leistung_heute
                        above: 25
                sequence:
                  - service: input_boolean.turn_off
                    target:
                      entity_id: input_boolean.speicher_eco_netzladen
                    data: {}
                  - service: input_number.set_value
                    data:
                      value: >-
                        {{ states('sensor.electricity_price_meinestrasse_123')|
                        float(0) }}
                    target:
                      entity_id: input_number.ladepreis
                    alias: Ladepreis Helfer nach aktuellem Strompreis
                  - service: input_select.select_option
                    metadata: {}
                    data:
                      option: BYD Akku Automatisch
                    target:
                      entity_id: input_select.byd_akkusteuerung
    enabled: true
mode: single
