alias: Akkusteuerung
description: ""
trigger:
  - platform: state
    entity_id:
      - input_select.akkusteuerung_sma_wr
      - input_number.akkusteuerung_ladestaerke_soll
      - input_number.akkusteuerung_entladestaerke_soll
    from: null
    to: null
    for:
      hours: 0
      minutes: 0
      seconds: 1
  - platform: time_pattern
    minutes: /30
    enabled: true
  - platform: homeassistant
    event: start
condition: []
action:
  - alias: Wenn Akku schnell Laden ...
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Akku schnell Laden
    then:
      - service: modbus.write_register
        data:
          hub: sma-sr_wr
          address: 40151
          slave: 3
          value:
            - 0
            - 802
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: modbus.write_register
        data:
          hub: sma-sr_wr
          address: 40149
          slave: 3
          value:
            - 65535
            - >-
              {{ 65535 - states('input_number.akkusteuerung_ladestaerke_soll') |
              int }}
  - alias: Wenn Akku schnell Entaden ...
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Akku schnell Entladen
    then:
      - service: modbus.write_register
        data:
          hub: sma-sr_wr
          address: 40151
          slave: 3
          value:
            - 0
            - 802
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: modbus.write_register
        data:
          hub: sma-sr_wr
          address: 40149
          slave: 3
          value:
            - 0
            - >-
              {{ states('input_number.akkusteuerung_entladestaerke_soll') |
              int }}
  - alias: Wenn Akku Pause ...
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Akku Pause
    then:
      - service: modbus.write_register
        data:
          hub: sma-sr_wr
          address: 40151
          slave: 3
          value:
            - 0
            - 802
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: modbus.write_register
        data:
          hub: sma-sr_wr
          address: 40149
          slave: 3
          value:
            - 0
            - 0
  - if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Akku Automatisch
    then:
      - service: modbus.write_register
        data:
          hub: sma-sr_wr
          address: 40151
          slave: 3
          value:
            - 0
            - 803
    alias: Wenn Akku Automatik
  - alias: Wenn Akku 0.2C Laden
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Akku 0.2C Laden
    then:
      - service: modbus.write_register
        data:
          hub: sma-sr_wr
          address: 40151
          slave: 3
          value:
            - 0
            - 802
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: modbus.write_register
        data:
          hub: sma-sr_wr
          address: 40149
          slave: 3
          value:
            - 65535
            - >-
              {{ 65535 - states('input_number.akkusteuerung_02c_ladestaerke') |
              int }}
mode: single
