alias: GGC bei Bedaf
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.sma_ggc_hm
    below: 1
condition: []
action:
  - service: modbus.write_register
    metadata: {}
    data:
      hub: sma-hm
      value:
        - #GGC ersten 5 Nummern
        - #GGC letzten 5 Nummern
      address: 43090
      slave: 1
mode: single
